=== prerana-u/WSD/food.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="Menu">
  <xs:complexType>
<xs:sequence>
   <xs:element name="Appetiser">
   <xs:complexType>
    <xs:sequence>
      <xs:element name="FoodItem" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
        
            <xs:element name="name" type="xs:string" />
            <xs:element name="price" type="xs:integer"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="spice" >
                    <xs:simpleType>
                          <xs:restriction base="xs:string">
                                <xs:enumeration value="Spicy"/>
                                <xs:enumeration value="Mildly Spicy"/>
                                <xs:enumeration value="Not Spicy"/>
                          </xs:restriction>
                  </xs:simpleType>
            </xs:element>
            <xs:element name="calories">
              <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="([0-9])*"/>
                  </xs:restriction>
              </xs:simpleType>
            </xs:element>

        </xs:sequence>
      </xs:complexType>
      </xs:element>
</xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:element name="Mains" >
   <xs:complexType>
<xs:sequence>
      <xs:element name="FoodItem" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
        
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:integer"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="spice" >
                    <xs:simpleType>
                          <xs:restriction base="xs:string">
                                <xs:enumeration value="Spicy"/>
                                <xs:enumeration value="Mildly Spicy"/>
                                <xs:enumeration value="Not Spicy"/>
                          </xs:restriction>
                  </xs:simpleType>
            </xs:element>
            <xs:element name="calories">
              <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="([0-9])*"/>
                  </xs:restriction>
              </xs:simpleType>
            </xs:element>

        </xs:sequence>
      </xs:complexType>
      </xs:element>

      
</xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:element name="Dessert">
   <xs:complexType>
<xs:sequence>
      <xs:element name="FoodItem" maxOccurs="unbounded">
      <xs:complexType>
        <xs:sequence>
        
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:integer"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="spice" >
                    <xs:simpleType>
                          <xs:restriction base="xs:string">
                                <xs:enumeration value="Spicy"/>
                                <xs:enumeration value="Mildly Spicy"/>
                                <xs:enumeration value="Not Spicy"/>
                          </xs:restriction>
                  </xs:simpleType>
            </xs:element>
             <xs:element name="calories">
              <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="([0-9])*"/>
                  </xs:restriction>
              </xs:simpleType>
            </xs:element>

        </xs:sequence>
      </xs:complexType>
      </xs:element>
</xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== prerana-u/WSD/food.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="foodstyle.xsl"?>

<Menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="food.xsd">

    <Appetiser>
        <FoodItem>
            <name>Vegetable Manchurian</name>
            <price>150</price>
            <description>
            Vegetable Manchurian in a delicious gravy.
            </description>
            <spice>Spicy</spice>
            <calories>250</calories>
        </FoodItem>

        <FoodItem>
            <name>French Fries</name>
            <price>120</price>
            <description>
            Fried Potatoes served with Mayonaisse on the side.
            </description>
            <spice>Not Spicy</spice>
            <calories>400</calories>
        </FoodItem>

        <FoodItem>
            <name>Baked Potatoes</name>
            <price>250</price>
            <description>
            Potatoes baked with cheesy goodness and served with Barbeque Sauce.
            </description>
            <spice>Mildly Spicy</spice>
            <calories>350</calories>
        </FoodItem>

    </Appetiser>

    <Mains>

        <FoodItem>
            <name>French Toast</name>
            <price>250</price>
            <description>
            Thick slices made from our homemade sourdough bread
            </description>
            <spice>Not Spicy</spice>
            <calories>500</calories>
        </FoodItem>

        <FoodItem>
            <name>Pasta in Alfredo Sauce</name>
            <price>395</price>
            <description>
            Pasta served with a delicious Alfredo Sauce.
            </description>
            <spice>Mildly Spicy</spice>
            <calories>950</calories>
        </FoodItem>

    </Mains>

    <Dessert>

        <FoodItem>
            <name>Chocolate Cake</name>
            <price>350</price>
            <description>
            Delicious chocolate cake topped with chocolate chips. 
            </description>
            <spice>Not Spicy</spice>
            <calories>500</calories>
        </FoodItem>
        <FoodItem>
            <name>Belgian Waffles</name>
            <price>250</price>
            <description>
            Light Belgian waffles covered with strawberries and whipped cream.
            </description>
            <spice>Not Spicy</spice>
            <calories>600</calories>
        </FoodItem>

        <FoodItem>
            <name>Tiramisu</name>
            <price>350</price>
            <description>
            Tiramisu is a coffee-flavoured Italian dessert.
            </description>
            <spice>Not Spicy</spice>
            <calories>640</calories>
        </FoodItem>

    </Dessert>

</Menu>
